image: python:3.8

stages:
  - build

test:
  variables:
    PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
  cache:
    key: pre-commit
    paths:
      - .cache/pre-commit
  stage: build
  before_script:
    - pip install virtualenv poetry pre-commit
    - virtualenv venv
    - source venv/bin/activate
    - poetry config virtualenvs.create false
    - poetry install --no-root
    - python manage.py migrate
    - python manage.py collectstatic --noinput
  script:
    - pre-commit run -a --hook-stage manual
    - python manage.py test
  artifacts:
    reports:
      junit: report.xml
