version: "3.9"

services:
  redis:
    image: redis
  db:
    image: postgres:14-bullseye
    user: ${UID:-1000}:${UID:-1000}
    stop_signal: SIGINT # Fast shutdown.
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      # - POSTGRES_DB=${DB_NAME}
      # - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - "./misc/dbdata:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -U postgres"]
      timeout: 30s
      interval: 5s
  web:
    command: >
      bash -c "./manage.py migrate;
               ./manage.py createsuperuser --no-input;
               while :;
               do exec ./manage.py runserver_plus 0.0.0.0:8000;
               done;
               "
    image: "web"
    user: ${UID:-1000}:${UID:-1000}
    build: .
    stop_signal: SIGINT # The devserver only stops on SIGINT.
    stdin_open: true
    tty: true
    volumes:
      - .:/code:cached
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - IN_DOCKER=True
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
  webserver:
    image: jumanjiman/caddy
    depends_on:
      - web
    ports:
      - "80:8000"
    command: -conf /code/misc/caddyfile.conf
    volumes:
      - .:/code:cached
