# Generated by Django 4.1.1 on 2022-09-16 21:32
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="art",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="artimage",
            name="caption",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="artimage",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
