# Generated by Django 4.1.1 on 2022-09-17 03:01
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_art_description_alter_artimage_caption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artimage",
            name="image",
            field=models.ImageField(upload_to="art/"),
        ),
    ]
