# Generated by Django 4.1.1 on 2022-09-18 00:56
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_artimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artimage",
            name="art",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="art_images",
                to="main.art",
            ),
        ),
    ]
