# Generated by Django 4.1.1 on 2022-09-19 20:46
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_artimage_art"),
    ]

    operations = [
        migrations.AddField(
            model_name="writing",
            name="teaser",
            field=models.CharField(default="content", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="art",
            name="slug",
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="art",
            name="title",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="artimage",
            name="title",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="writing",
            name="slug",
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="writing",
            name="title",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
