# Generated by Django 4.1.1 on 2022-10-03 00:59
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_content_image_remove_artimage_art_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="caption",
        ),
    ]
