# Generated by Django 4.1.1 on 2022-10-04 01:21
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_remove_image_caption"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={"ordering": ["-publish_date"]},
        ),
        migrations.RenameField(
            model_name="content",
            old_name="created_on",
            new_name="create_date",
        ),
        migrations.RenameField(
            model_name="content",
            old_name="updated_on",
            new_name="update_date",
        ),
        migrations.AddField(
            model_name="content",
            name="publish_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
