# Generated by Django 4.1.1 on 2022-10-04 01:30
import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_content_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="publish_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 10, 4, 1, 29, 59, 986012, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
