# Generated by Django 4.1.1 on 2022-10-04 01:30
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_content_publish_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="publish_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
