# Generated by Django 4.1.1 on 2022-10-04 21:32
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_content_publish_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Image",
            new_name="ContentImage",
        ),
    ]
