# Generated by Django 4.1.1 on 2022-10-04 23:01
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_contentimage_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentimage",
            name="image_thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="thumbnail/"),
        ),
    ]
