# Generated by Django 4.1.1 on 2022-10-04 23:20
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_contentimage_image_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentimage",
            name="image_thumbnail",
        ),
    ]
