# Generated by Django 4.1.3 on 2022-11-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentimage',
            name='image_size',
            field=models.IntegerField(choices=[(0, 'Auto'), (1, '100%'), (2, '50%'), (3, '25%')], default=0),
        ),
    ]
