# Generated by Django 4.1.3 on 2022-11-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_contentimage_image_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentimage",
            name="image_size",
            field=models.IntegerField(
                choices=[
                    (0, "Auto"),
                    (1, "100%"),
                    (2, "66%"),
                    (3, "50%"),
                    (4, "33%"),
                    (5, "25%"),
                ],
                default=0,
            ),
        ),
    ]
