name: Django CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2
      - name: View Poetry --help
        run: poetry --help
      - uses: pre-commit/action@v2
